kabsmake: kabsDImaxtree2.c
	gcc -O3 -I../Dist kabsDImaxtree2.c -o kabs -lfreeimage -lm
gaussmake: gaussianblur.c
	gcc -O3 -I../Dist gaussianblur.c -o gauss -lfreeimage -lm
unsharpmake: unsharpmasking.c
	gcc -O3 -I../Dist unsharpmasking.c -o usm -lfreeimage
all: kabsmake gaussmake unsharpmake